kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBtqPF4AW3Tr+TttZp/vbFEwzvf5w/cyY0YYQ3ePdFhtf1+cmJqLdoaqcJYFthWpWl+GQHfh9ar3iGFEkW82Fau2IsmB2qj7Xw7chro/kN/31aoipLyZfmWHK8yx0oe83OYyXbQYSt2L8Iyp3y5lindGkbSVgJTiB2CwBRRDsz/bPonAuTLNbaN+jWSFUbHBkhYptvKeAJeVnbE4XkJAfKLACVGcCBRq8nhY7/933yz3fLK62Q9fLbcCtYWxet2luuW7qD0SvL8EbFOrYJrk6QUf7+KsDuMK2E3M9H9XQwL/Zwb09mFbEfK76Dl/sgHwxLCCkpdOrwPc6IThv3A6vTjz63lqj+NRIDJwpdRbogVzyxkNlcyVZ4ml5ZAapm150JEGDmNZhZfA3hBSIGhRa3an6hCHPsmbQFTCuDRrYsyhHoY0VWIS+nSwiCK5l4zfzU6GdJUI/osTNlxNySAAnQQ5N7xoGaGaOuSoU0Rcetz92EZmhivlrKQy/tH6w7C0rKkdrvEtRXlKADRRyQFCd22OOzjr6eBLYcNfm2pOuWK6RPm9OcIqouGo9HwAop1wCBHhuT09nAgybXkZVaCXfhxeC+n7W4n5cjMbWSoI08RWI06ntbAy8ujbEXTWarqxPUpBG3gTZ0uo1OYJr8jbInsVgTJPjNZL6TRkSAntb1PVmS7m8jEYmrB8GK8QOY0D0aCg3GCTDL9acaHb1WBMQ==
    admin-user: AgCggnrnVfuO3J4p6yxyuq0g1RdtxUqOQUvEa692qaeqyIqLDqhpCe5/HIxa8aj7wWA1+H8B5atDvwtO39IBrHIPxrGTEkhQnfPzBOCiwV03qJStvTPIfwsWarg8sLwTV2ujdq9jBDDq9Xuob4Ski8M/tRTL/HU8FVzqE43IASpU794vOT7XUJBKfJ2CPUVSymJD4WQvtLB1Ng8TaKyZd5PXn66ABmG0Q5jLh/aA7BhesbBlKa+MUuI/ZpzW9FE2/RCxY+N34iJkgQFoY+3gPgip6YwXys7AIsxYRv+1oauXr2nn5F6VZtGaueVlD8lq87nFlFEJEtbRiI/j7fQhXuskQYUuhwW/JOOvojmCetVNi231gQvtyRXvSlUYGzbnKE6ImTYizMhw9h+W9k89KPuOCt/04UC6LHKgOgklNfoDLh38XnqU+FXZPJELReaPSt9+W2I9RTUs2HMYVyh0VpzNhPzcjIeDq6GsB0FrEPQVrVNmJHLgiPMVQ7RbfQSfuKcIIulenCgbkKUW5kK52DAdqjU9BZFgj/mmBc7bAxb42f0Wb/F8ouqve5eA3s++T50DvZcHWLoQ44AQ5Go9tAS7mZaxyQa4vVfxpwG/Aa/vZqF7AhxJrS3cWJLxWvz/Bt2JmoHAhiJSSppjDkJa9hBEjaSg6BOZOOLxTh/16in/EDoZ6df3Ra2NFBU6BbIb3ceL2eOgnhA=
